### ISSUE TITLE
500 error in Delete action for returned proposals

### ISSUE THREAD

**Issue by maccraymer** [ISO-TC211/iso-geodetic-registry#102]
See PR #36. The HTTP Status 500 error has returned when selecting the Delete action for a returned proposal in the Submission Organization folder. The only way for a submitter to delete a returned proposal is to submit it again and then select the Withdraw action.

**Comment by florianesser** [comment]
Thanks for the report, @maccraymer ! What item class did the item have that you tried to delete? This information is essential because behaviour can be different for different item classes.

It would be helpful if you could include that info in all your item-related bug reports (or even a link to a reproduction case in the staging registry if that's feasible).

**Comment by maccraymer** [comment]
Sorry for not posting the details of what generated the error. I had tried a few different items:

Clarification of geodetic CRS (item 205 IGS08-XYZ)
Clarification of vertical datum (item 140 CGVD2013a)
Addition of new transformation (null position vector transformation)

However, when I used the Delete action today, I no longer get the error!! I have no idea why I was getting it Saturday night just after midnight. This Sunday afternoon I tried the following items:

Clarification of geodetic datum (item 106 IGS08)
Clarification of vertical datum (item 140 CGVD2013a)
Clarification of transformation (item 461 ITRF89-ITRF2008)
Clarification of geodetic CRS (item 205 IGS08-XYZ)
Addition of new transformation (null position vector transformation)

Deleting works fine on all those. So I'm closing this issue again! Sorry for the trouble.
