### ISSUE TITLE
Make citations editable in Clarifications

### ISSUE THREAD

**Issue by maccraymer** [ISO-TC211/iso-geodetic-registry#94]
When selecting the Clarify action for an item, all information is editable except the citations. These should also be editable in order to correct minor things like typos.

**Comment by florianesser** [comment]
@maccraymer This is not a simple change, unfortunately. The clarification mechanism was originally developed so that only text attributes of the item itself can be changed. Citations, however, are implemented in their own class `CI_Citation` which is referenced from the item and, therefore, can't be edited as part of a clarification.

While this could certainly be implemented, I'd suggest that we focus on #50 instead.

**Comment by maccraymer** [comment]
I agree. If we can implement #50 instead, that should make citations editable as separate items and be a better solution all around. I was just hoping there might be a simpler way in the interim. I'll close this issue.
